# Обзор матричной алгебры

In [21]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

### Поэлементные операции с массивами

In [4]:
x + y

array([5, 7, 9])

In [5]:
x * y

array([ 4, 10, 18])

In [6]:
x - y

array([-3, -3, -3])

In [7]:
 x / y

array([0.25, 0.4 , 0.5 ])

In [8]:
x ** y

array([  1,  32, 729], dtype=int32)

In [9]:
y % x

array([0, 1, 0], dtype=int32)

### Изменение размерности

In [10]:
x = np.arange(0, 10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 10 - количество строк (сначала всегда идет количество строк, потом количество столбцов, т.е (10,)- 
# oзначает 10 строк, один столбец)
x.shape

(10,)

In [12]:
np.array(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
).shape

(3, 2)

In [13]:
# первый аргумент - количество строк
# второй - количество столбцов

x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
# при "неправильном" количестве строк и столбцов будет ошибка

x.reshape( 5, 3 )

ValueError: cannot reshape array of size 10 into shape (5,3)

In [ ]:
d = {'a': 1}

In [ ]:
d['b']

In [ ]:
# Если нужно, чтобы скрипт не вылетал с ошибкой, то можно так
try:
    x.reshape(5, 3)
    x += '1'

except ValueError:
    print('Попались кривые данные, идём дальше')

except Exception as err:
    print('Неизвестная ошибка. Останавливаю выполнение')
    raise err

In [ ]:
# транспонирование матриц

np.array(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
).T

In [ ]:
# склеивание листов

x = np.array([ [1, 2, 3], [4, 5, 6] ])

In [ ]:
x.ravel()

In [ ]:
x = np.array( [ [1, 2, 3], [4, 5, 6] ] )

In [ ]:
# или можно так
x.reshape(6)

In [ ]:
x = np.array( [ [1, 2, 3], [4, 5, 6] ] )

In [ ]:
# результат разный, если добавить 1 в качестве количества строк

x.reshape( 1, 6 )[0]

In [ ]:
x

### Скаляроное произведение векторов

\begin{equation*}
\LARGE
\vec{a} \dot{} \vec{b} = |\vec{a}| \space |\vec{b}| \space cos(\vec{a}, \vec{b})
\end{equation*}

Пусть 
\begin{equation*}
\LARGE
\vec{a} = (a_1, a_2, a_3) \\
\LARGE
\vec{b} = (b_1, b_2, b_3)
\end{equation*}

Тогда скалярное произведение векторов равно
\begin{equation*}
\LARGE
\vec{a} \dot{} \vec{b} = a_1 b_1 + a_2 b_2 + a_3 b_3
\end{equation*}

In [ ]:
a = np.array([4, 3])
b = np.array([2, 1])

In [ ]:
np.dot(a, b)

Можно посчитать и таким образом

In [ ]:
# первый шаг

for pair in zip(a, b):
    print(pair)

In [ ]:
# второй шаг

[pair[0] * pair[1] for pair in zip(a, b)]

In [ ]:
# итоговый результат

sum([pair[0] * pair[1] for pair in zip(a, b)])

### Косинусное расстояние между векторами

\begin{equation*}
\LARGE
cos(\vec{a}, \vec{b}) = \frac{\vec{a} \dot{} \vec{b}}{|\vec{a}| \space |\vec{b}|}
\end{equation*}

In [ ]:
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
ax = plt.axes()
plt.xlim([0, 5])
plt.ylim([0, 4])

ax.arrow(0, 0, a[0], a[1], head_width=.1, head_length=.2, fc='k', ec='k')
ax.arrow(0, 0, b[0], b[1], head_width=.1, head_length=.2, fc='k', ec='k')

plt.show()

In [ ]:
def cosine(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    a_length = np.linalg.norm(a)
    b_length = np.linalg.norm(b)
    
    return np.dot(a, b) / (a_length * b_length)

In [ ]:
# длины векторов можно было считать и так

a_length = np.sqrt((a ** 2).sum())
b_length = np.sqrt((b ** 2).sum())

In [ ]:
cosine(a, b)

In [ ]:
# Угол между векторами в радианах

np.arccos(cosine(a, b))

In [ ]:
# угол между векторами в градусах

np.arccos(cosine(a, b)) * 360 / (2 * np.pi)

### Упражнение

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [ ]:
from IPython.display import Image
# Image("user_matrix.JPG")

Матрица в виде numpy array

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [ ]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

### Перемножение матриц

**Определение**

Пусть даны две матрицы a и b размером l x m и m x n соответственно. l - количество строк, n - количество столбцов.

\begin{equation*}
\LARGE
a = 
\begin{bmatrix}
    a_{11} & a_{12} \dots a_{1m} \\
    a_{21} & a_{22} \dots a_{2m} \\
    \vdots & \vdots \dots \vdots \\
    a_{l1} & a_{l2} \dots a_{lm}
\end{bmatrix}
\end{equation*}

<br>

\begin{equation*}
\LARGE
b = 
\begin{bmatrix}
    b_{11} & b_{12} \dots b_{1n} \\
    b_{21} & b_{22} \dots b_{2n} \\
    \vdots & \vdots \dots \vdots \\
    b_{m1} & b_{m2} \dots b_{mn}
\end{bmatrix}
\end{equation*}

Тогда произведением матриц a и b будет матрица c размерностью l x n:

\begin{equation*}
\LARGE
c = 
\begin{bmatrix}
    c_{11} & c_{12} \dots c_{1n} \\
    c_{21} & c_{22} \dots c_{2n} \\
    \vdots & \vdots \dots \vdots \\
    c_{l1} & c_{l2} \dots c_{ln}
\end{bmatrix}
\end{equation*}

<br>

\begin{equation*}
\LARGE
c_{ij} = \sum_{k=1}^m a_{ik} b_{kj}
\end{equation*}

<img src = 'https://wikimedia.org/api/rest_v1/media/math/render/svg/1f96c71f0a99eac3ee872e7baf22e84324d7b4c9' style="width: 80%"></img>

In [ ]:
next_user_stats.shape

In [ ]:
cosine(users_stats[7], next_user_stats)

In [ ]:
my_list = []
for i in range(10):
    my_list.append(round(np.arccos(cosine(users_stats[i], next_user_stats)) * 360 / (2 * np.pi), 2))
    print(f'Пользователь номер {i+1}', round(np.arccos(cosine(users_stats[i], next_user_stats)) * 360 / (2 * np.pi), 2))

In [ ]:
sorted(my_list)

In [ ]:
a = [
    [1, 2],
    [3, 4]
]
b = [
    [5, 6],
    [7, 8]
]

In [ ]:
np.dot(a, b)

В numpy есть специальный тип matrix, который отличается от ndarray

In [ ]:
a_matrix = np.matrix([[1, 2], [3, 4]])
b_matrix = np.matrix([[5, 6], [7, 8]])

In [ ]:
a_matrix * b_matrix

# Линейные уравнения

Дана система линейных уравнений

\begin{equation*}
\LARGE
x + 3*y = 9 \\
\LARGE
2*x - 4*y = 8
\end{equation*}

In [22]:
# коэффициенты при переменных в левой части уравнения

a = np.array(
    [
        [1, 3], [2, -4]
    ]
)

In [15]:
# Значения в правой чассти уравнения

b = np.array([9, 8])

In [23]:
# решение

answer = np.linalg.solve(a, b)

answer

array([6., 1.])

In [24]:
# проверка правильности решения

np.allclose(np.dot(a, answer), b)

True

### Определитель матрицы


In [26]:
a = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

In [27]:
np.linalg.det(a)

-2.0000000000000004

In [28]:
# Как получить единичную матрицу
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### Сингулярное разложение

M - матрица m x n

$\sigma$ является сингулярным числом матрицы M, если существуют два вектора единичной длины u и v такие, что

\begin{equation*}
\LARGE
Mv = \sigma u \\ 
\LARGE
и \space M* u = \sigma v
\end{equation*}

Сингулярное разложение:

\begin{equation*}
\LARGE
M = U \sigma V^*
\end{equation*}